import Sidebar from "../components/sidebar";
import "../styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full w-full">
      <body className=" h-full">
        <div className="flex h-full w-full">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
